---
apiVersion: v1
kind: Namespace
metadata:
  name: spring-petclinic

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: javaapp
  name: javaapp
  namespace: spring-petclinic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: javaapp
  template:
    metadata:
      labels:
        app: javaapp
    spec:
      containers:
      - image: df7854c892e3/web:<TAG>
        imagePullPolicy: Always
        name: javaapp

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: javaapp
  name: javaapp
  namespace: spring-petclinic
spec:
  ports:
  - nodePort: 32223
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: javaapp
  type: NodePort
