apiVersion: apps/v1
kind: Deployment
metadata:
  name: javaapp-deployment
  labels:
     app: javaapp
     type: web-app
spec:
  template:
     metadata:
       name: javaapp-pod
       labels: 
         app: javaapp
         type: web-app
     spec:
         containers:
           - image: "df7854c892e3/web:<TAG>"
             imagePullPolicy: Always
             name: javaapp
  replicas: 1
  selector:
    matchLabels:
      type: web-app
---
apiVersion: v1
kind: Service
metadata:
  name: javaapp-service
spec:
  selector:
    app: javaapp
  type: LoadBalancer  
  ports:
    - protocol: TCP
      targetPort: 8080
      port: 80
      nodePort: 8080
