/* ---
apiVersion: v1
kind: Namespace
metadata:
  name: kube-public

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: web
  name: web
  namespace: kube-public
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - image: df7854c892e3/web:<TAG>
        imagePullPolicy: Always
        name: web

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: web
  name: web
  namespace: kube-public
spec:
  ports:
  - nodePort: 32223
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: web
  type: NodePort
 */ 
  
apiVersion: apps/v1
kind: Deployment
metadata:
  name: javaapp-deployment
  labels:
     app: javaapp
     name: javaapp
spec:
  template:
     metadata:
       name: javaapp-pod
       labels: 
         app: javaapp
     spec:
         containers:
           - image: "df7854c892e3/web:<TAG>"
             imagePullPolicy: Always
             name: javaapp

---
apiVersion: v1
kind: Service
metadata:
  name: javaapp-service
spec:
  selector:
    app: javaapp
  type: LoadBalancer  
  ports:
    - protocol: TCP
      targetPort: 8080
      port: 80
      nodePort: 8080
